title: Matheus Calegaro
email: hello@matheus.me
description: >-
  Hello, my name is Matheus Calegaro and I'm a Software Developer based in Brazil. Come here to check my Resume, Experiences and Projects :)
baseurl: ""
url: "https://matheus.me"
social:
  linkedin: mathcale
  github: mathcale
  codepen: mathcale

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
